AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Automate an ETL processing pipeline for COVID-19 data using Python and AWS

Resources:
  ETLLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ETLLayer
      Description: Contains libraries necessary for ETLLambda
      ContentUri: layers/
      CompatibleRuntimes:
        - python3.8

ETLLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ETLLambda
      Handler: etl.lambda_handler
      Runtime: python3.8
      CodeUri: etl.lambda_handler
      Description: A function that performs the ETL job
      Layers:
        - !Ref ETLLayer
      Events:
        MyCloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 16 ? * * *)

  MyDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: MyDynamoDBTable

  NotifySNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Notify_subscriber
      Subscription:
        - Endpoint: "pedramadili@gmail.com"
          Protocol: email
