AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Automate an ETL processing pipeline for COVID-19 data using Python and AWS

Resources:
  ETLLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ETLLayer
      Description: Contains libraries necessary for ETLLambda
      ContentUri: .
      CompatibleRuntimes:
        - python3.8

  ETLLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ETLLambda
      CodeUri: .
      Handler: etl.lambda_handler
      Runtime: python3.8
      Description: A function that performs the ETL job
      MemorySize: 512
      Timeout: 120
      Layers:
        - !Ref ETLLayer
      Environment:
        Variables:
          nyt_url: https://raw.githubusercontent.com/nytimes/covid-19-data/master/us.csv
          jh_url: https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv
          db_table: !Ref COVID19Table
          sns_topic: !Ref NotifySNS
      Events:
        MyCloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(15 22 ? * * *)

  COVID19Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: covid-19-table

  NotifySNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Notify_Pedram
      Subscription:
        - Endpoint: "pedramadili@gmail.com"
          Protocol: email
